### ISSUE TITLE
Can I disable metrics with an option or are they auto disabled? 

### ISSUE THREAD

**Issue by stahnma** [flox/install-flox-action#93]

**Comment by stahnma** [comment]
In the action can we have a parameter to explicitly disable metric sending? 

What are doing to the sentry side of metrics? if CI=true is set, the header and sending to the catalog service is processed appropriately.

**Comment by sschuberth** [comment]
Could this (and also the other [inputs](https://github.com/flox/install-flox-action/blob/a25f820b52f45ac0955289ccbb1184267b5abbe3/action.yml#L9-L26)) please be also documented in the `README.md`?
